### ISSUE TITLE
AppStore

### ISSUE THREAD

**Issue by ghost** [100mango/ColorPicker#1]
Hi, In appstote is another version?

**Comment by 100mango** [comment]
Yes. It's version 1.0

**Comment by ghost** [comment]
You can send me a version from the AppStore because at the github not work with certain features, and I would like to see the code

**Comment by 100mango** [comment]
Please download the project and  reset by yourself.

**Comment by ghost** [comment]
You can add a translation in English? Because, I don't know Chinese :(

**Comment by 100mango** [comment]
Which part do you need for a translation?  The code comments or the project description?  I am glad to help you if I have enough time. I am dealing some work these days.By the way, where are you from? It seems like that you are not from a native English speaker country.
